Add execution order test
reactphp/async pull request #63
Opened 2022-08-27 09:45 UTC by kelunik

This test currently has a different execution order in my adapter, so let's document the expected execution order.

2022-09-05 16:05 UTC, SimonFrings requested changes
Hey @kelunik, thanks for your work on this :+1: 

I suggested a few changes below. Can you also place this test a bit lower in this test class. We try to have the easiest/simplest tests at the top and it progresses in complexity as you go down.

2022-09-05 16:05 UTC, SimonFrings commented on tests/AwaitTest.php
> +        })();
In my opinion it makes more sense to expect an `abcd` outcome instead of adjusting the outcome to the written test.
```suggestion
        self::expectOutputString('abcd');

        $deferred = new React\Promise\Deferred();

        $promises[] = React\Async\async(function () use ($deferred, $await) {
            print 'a';
            $await($deferred->promise());
            print 'c';
        })();

        $promises[] = React\Async\async(function () use ($deferred) {
            print 'b';
            $deferred->resolve();
            print 'd';
        })();
```

2022-09-05 16:05 UTC, SimonFrings commented on tests/AwaitTest.php
> +        $deferred = new React\Promise\Deferred();
We use `use operators` in our tests, this makes them easier to read and understand (especially longer tests)
```suggestion
        $deferred = new Deferred();
```
This occurs a few times in your test.

2022-09-07 18:00 UTC, kelunik commented on tests/AwaitTest.php
```suggestion
use function React\Promise\all;

```

2022-09-07 18:00 UTC, kelunik commented on tests/AwaitTest.php
> +        $promises[] = React\Async\async(function () use ($deferred, $await) {
```suggestion
        $promises[] = async(function () use ($deferred, $await) {
```

2022-09-07 18:00 UTC, kelunik commented on tests/AwaitTest.php
> +        $promises[] = React\Async\async(function () use ($deferred) {
```suggestion
        $promises[] = async(function () use ($deferred) {
```

2022-09-07 18:00 UTC, kelunik commented on tests/AwaitTest.php
> +        $await(React\Promise\all($promises));
```suggestion
        $await(all($promises));
```

2022-09-07 18:02 UTC, kelunik commented
@SimonFrings Done. 👍

2022-09-09 11:32 UTC, SimonFrings commented
@kelunik thanks for the update 👍

The test itself in its functionality and the overall design looks great. I talked with @clue about this and it looks like your testcase is already covered by other tests and didn't raise the overall code coverage.

I would argue that it wouldn't make sense to add a test just to show a specific example of what is possible.

2023-10-24 15:50 UTC, clue commented
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. If you feel this is still relevant, please come back with more details and we can always reopen this :+1: 

Thank you for your effort nonetheless, keep it up! :+1:

2023-10-24 15:50 UTC, closed without merging